import { Minus, Pause, Play, X, Copy, ArrowRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { formatSize } from '@/lib/mock-filesystem';
import type { TransferJob } from '@/lib/mock-transfers';

export function TransferStrip({ jobs, restore, dismiss }: { jobs: TransferJob[]; restore: (id: number) => void; dismiss: (id: number) => void }) {
  if (!jobs.length) return null;
  return <div className="transfer-strip" aria-label="Background transfers">{jobs.map(job => <div className="transfer-chip" key={job.id}><Button variant="ghost" onClick={() => restore(job.id)} aria-label={`Restore ${job.operation.type} transfer ${job.id}`}><Copy size={13} />{job.operation.type === 'copy' ? 'Copy' : 'Move'} {job.id >= 100000 ? `NAS #${job.id - 100000}` : `#${job.id}`} · {job.state === 'running' ? `${Math.round(job.processed / Math.max(1, job.total) * 100)}%` : job.state}{job.state === 'running' && ` · ${job.id >= 100000 ? '' : 'Sample '}${formatSize(job.rate ?? 0)}/s`}<progress className="transfer-chip-meter" aria-label={`Transfer ${job.id} progress`} value={job.processed} max={Math.max(1, job.total)} /></Button>{!['running', 'paused'].includes(job.state) && <Button variant="ghost" size="icon" title="Dismiss transfer" aria-label={`Dismiss transfer ${job.id}`} onClick={() => dismiss(job.id)}><X size={12} /></Button>}</div>)}</div>;
}

export function TransferWindow({ job, dark, minimize, togglePause, cancel }: { job: TransferJob | undefined; dark: boolean; minimize: () => void; togglePause: (id: number) => void; cancel: (id: number) => void }) {
  const pending = job?.state === 'running' || job?.state === 'paused';
  return <Dialog open={Boolean(job)} onOpenChange={open => { if (!open) minimize(); }}><DialogContent className={`${dark ? 'dark' : ''} transfer-dialog bg-background text-foreground`}><DialogHeader><DialogTitle>{job?.operation.type === 'move' ? 'Moving files' : 'Copying files'} — {job && job.id >= 100000 ? `NAS #${job.id - 100000}` : `#${job?.id}`}</DialogTitle><DialogDescription>{job && job.id >= 100000 ? 'Transfer on your NAS · keeps running if you close this page' : 'Sample-file transfer · No server data is being transferred.'}</DialogDescription></DialogHeader>{job && <><div className="transfer-path">{job.operation.source}<ArrowRight size={14} />{job.operation.destination}</div><div className="transfer-path">{job.operation.names.join(', ')}</div><progress className="transfer-meter" aria-label="Overall transfer progress" value={job.processed} max={Math.max(1, job.total)} /><div className="transfer-facts"><span>{formatSize(job.processed)} / {formatSize(job.total)}</span><span>{job.id >= 100000 ? '' : 'Sample rate · '}{job.state === 'running' ? `${formatSize(job.rate ?? 0)}/s` : job.state === 'paused' ? 'Paused' : '—'}</span><span role="status">{job.state}</span></div><p className="text-xs text-muted-foreground">{job.operation.names.length} selected items · {job.id >= 100000 ? 'Progress is reported by your NAS.' : 'Simulated sample transfer rate; no server data transferred.'}</p>{job.error && <p role="alert" className="text-destructive text-sm">{job.error}</p>}<DialogFooter>{pending && <><Button variant="outline" onClick={() => togglePause(job.id)}>{job.state === 'paused' ? <Play size={14} /> : <Pause size={14} />}{job.state === 'paused' ? 'Resume' : 'Pause'}</Button><Button variant="outline" onClick={() => cancel(job.id)}><X size={14} />Cancel transfer</Button></>}<Button aria-label={pending ? "Background" : "Close transfer window"} onClick={minimize}><Minus size={14} />{pending ? 'Background' : 'Close'}</Button></DialogFooter></>}</DialogContent></Dialog>;
}